"""Generate SI Table S10 from the saved split-allocation sensitivity analysis.

The table compares both selected rules on the common 1,298 test questions,
using the primary grader. CSV summaries retain both graders. Error percentiles
are recomputed from saved partition results; no model calls or grading occur.
"""
from pathlib import Path
import argparse
import csv
import json
import math
import statistics

ROOT = Path(__file__).resolve().parents[1]
MODELS = {'gemini35flash':'Gemini','sonnet46':'Sonnet','deepseekv32maas':'DeepSeek'}
ALPHAS = (.20,.25,.30,.35,.40)


def rate(value):
    percent=100*float(value)
    return r'$<0.1$' if 0<percent<.05 else f'{percent:.1f}'


def summarize_errors(rows):
    errors=[]
    for row in rows:
        n=int(row['common_n_answered'])
        if n:
            error=float(row['common_observed_error'])
            assert math.isclose(error,int(row['common_n_incorrect'])/n)
            errors.append(error)
        else:
            assert row['common_observed_error']==''
    if not errors:
        return {'n_partitions_with_test_answers':0,'median_common_test_error':None,
                'common_test_error_q25':None,'common_test_error_q75':None}
    median=statistics.median(errors)
    q25,_,q75=statistics.quantiles(errors,n=4,method='inclusive') if len(errors)>1 else [median]*3
    return {'n_partitions_with_test_answers':len(errors),'median_common_test_error':median,
            'common_test_error_q25':q25,'common_test_error_q75':q75}


def error_tex(summary):
    n=summary['n_partitions_with_test_answers']
    if not n:return '---'
    median=f"{100*summary['median_common_test_error']:.1f}"
    if n==1:return median
    return median+f" [{100*summary['common_test_error_q25']:.1f}, {100*summary['common_test_error_q75']:.1f}]"


def generate(source, out, primary_grader='openai'):
    if primary_grader not in ('openai','gemini'):
        raise ValueError('Unknown grader: '+primary_grader)
    meta=json.loads((source/'metadata.json').read_text())
    assert meta['additional_splits']==100 and meta['common_test_size']==1298
    assert meta['verification']['original_result_rows_reproduced']==3030
    with (source/'split_summary.csv').open() as stream: rows=list(csv.DictReader(stream))
    lookup={(r['model_key'],float(r['alpha']),r['grader'],r['allocation']):r for r in rows}
    assert len(lookup)==60
    groups={key:[] for key in lookup}
    with (source/'all_results.csv').open() as stream:
        for row in csv.DictReader(stream):
            if int(row['seed'])==meta['seed']:continue
            key=(row['model_key'],float(row['alpha']),row['grader'],row['allocation'])
            groups[key].append(row)
    assert all(len(group)==len({r['seed'] for r in group})==100 for group in groups.values())
    lines=['% Generated by analysis/make_split_sensitivity_table.py; do not edit values manually.']
    records=[]
    for model,label in MODELS.items():
        if records:lines.append(r'\midrule')
        for i,alpha in enumerate(ALPHAS):
            record={'model_key':model,'alpha':alpha,'display_grader':primary_grader}
            vals=[]
            for grader in ['openai','gemini']:
                pair=[lookup[model,alpha,grader,a] for a in ['50-50','70-30']]
                assert all(int(r['n_splits'])==100 for r in pair)
                for allocation,r in zip(['50-50','70-30'],pair):
                    group=groups[model,alpha,grader,allocation]
                    assert all(int(x['common_n_test'])==1298 for x in group)
                    summary=summarize_errors(group)
                    assert summary['n_partitions_with_test_answers']==int(r['n_supported'])
                    assert math.isclose(statistics.mean(float(x['common_answer_rate']) for x in group),
                                        float(r['mean_common_answer_rate']),abs_tol=1e-12)
                    if grader==primary_grader:
                        vals += [str(int(r['n_supported'])),rate(r['mean_common_answer_rate']),error_tex(summary)]
                    record[f'{grader}_{allocation}_n_supported']=int(r['n_supported'])
                    record[f'{grader}_{allocation}_mean_common_answer_rate']=float(r['mean_common_answer_rate'])
                    record.update({f'{grader}_{allocation}_{key}':value for key,value in summary.items()})
            records.append(record)
            if model=='deepseekv32maas':
                assert all(record[k] in (0,None) for k in record if k not in ['model_key','alpha','display_grader'])
                if i:continue
            prefix=(label if i==0 else '')+' & '+('All' if model=='deepseekv32maas' else f'${alpha:.2f}$')
            lines.append(prefix+' & '+' & '.join(vals)+r'\\')
    out.mkdir(parents=True,exist_ok=True)
    stem='TableS10_SplitSensitivity'
    (out/(stem+'_rows.tex')).write_text('\n'.join(lines)+'\n')
    with (out/(stem+'.csv')).open('w',newline='') as stream:
        writer=csv.DictWriter(stream,fieldnames=list(records[0]));writer.writeheader();writer.writerows(records)
    print('Generated '+str(out/(stem+'_rows.tex')))


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',type=Path,default=ROOT/'results/exploratory/threshold_split_sensitivity')
    parser.add_argument('--out-dir',type=Path,default=ROOT/'results/figures')
    parser.add_argument('--grader',choices=('openai','gemini'),default='openai',
                        help='Grader displayed in Table S10; the CSV retains both graders.')
    args=parser.parse_args();generate(args.source,args.out_dir,args.grader)
